// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwnorqpmlfxeqwphxeip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3bm9ycXBtbGZ4ZXF3cGh4ZWlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3ODAyNjcsImV4cCI6MjA2NDM1NjI2N30.WeXQym9x-qCCpeGN31c9_-HeAYTtCp41upoZIPyfQGk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);